In [4]:
import pandas as pd
import numpy as np

In [5]:
from google_play_scraper import reviews, Sort, app

In [6]:
APP_ID='com.application.zomato'
result, _ = reviews(
    APP_ID,
    lang='en',
    country='in',
    sort=Sort.NEWEST,
    count=30000
)

In [7]:
reviews_df=pd.DataFrame(result)

In [8]:
reviews_df=reviews_df[['content','score','thumbsUpCount','at','appVersion']]
reviews_df

,content,score,thumbsUpCount,at,appVersion
0,delicious,5,0,2026-03-26 18:27:59,19.4.7
1,I am really happy in this app,5,0,2026-03-26 18:26:42,19.3.9
2,👍🏻,5,0,2026-03-26 17:59:55,19.4.7
3,it cannot deliver in villages like agiaon bazar,2,0,2026-03-26 17:25:20,None
4,Zomato has no control on restaurants . Zomato ...,5,0,2026-03-26 17:10:15,19.4.7
...,...,...,...,...,...
29995,great,5,0,2026-02-22 16:22:31,None
29996,good,5,0,2026-02-22 16:21:12,19.2.1
29997,Nice,5,0,2026-02-22 16:20:34,19.3.4
29998,👍🏻,5,0,2026-02-22 16:20:29,19.3.7
29999,good,5,0,2026-02-22 16:20:03,None

In [9]:
reviews_df.rename(columns={
    'thumbsUpCount':'ThumbsUpCount',
    'appVersion':'AppVersion',
},inplace=True)

In [10]:
reviews_df

,content,score,ThumbsUpCount,at,AppVersion
0,delicious,5,0,2026-03-26 18:27:59,19.4.7
1,I am really happy in this app,5,0,2026-03-26 18:26:42,19.3.9
2,👍🏻,5,0,2026-03-26 17:59:55,19.4.7
3,it cannot deliver in villages like agiaon bazar,2,0,2026-03-26 17:25:20,None
4,Zomato has no control on restaurants . Zomato ...,5,0,2026-03-26 17:10:15,19.4.7
...,...,...,...,...,...
29995,great,5,0,2026-02-22 16:22:31,None
29996,good,5,0,2026-02-22 16:21:12,19.2.1
29997,Nice,5,0,2026-02-22 16:20:34,19.3.4
29998,👍🏻,5,0,2026-02-22 16:20:29,19.3.7
29999,good,5,0,2026-02-22 16:20:03,None

In [11]:
reviews_df['app']='Zomato'
reviews_df['platform']='Playstore'

In [12]:
reviews_df

,content,score,ThumbsUpCount,at,AppVersion,app,platform
0,delicious,5,0,2026-03-26 18:27:59,19.4.7,Zomato,Playstore
1,I am really happy in this app,5,0,2026-03-26 18:26:42,19.3.9,Zomato,Playstore
2,👍🏻,5,0,2026-03-26 17:59:55,19.4.7,Zomato,Playstore
3,it cannot deliver in villages like agiaon bazar,2,0,2026-03-26 17:25:20,None,Zomato,Playstore
4,Zomato has no control on restaurants . Zomato ...,5,0,2026-03-26 17:10:15,19.4.7,Zomato,Playstore
...,...,...,...,...,...,...,...
29995,great,5,0,2026-02-22 16:22:31,None,Zomato,Playstore
29996,good,5,0,2026-02-22 16:21:12,19.2.1,Zomato,Playstore
29997,Nice,5,0,2026-02-22 16:20:34,19.3.4,Zomato,Playstore
29998,👍🏻,5,0,2026-02-22 16:20:29,19.3.7,Zomato,Playstore
29999,good,5,0,2026-02-22 16:20:03,None,Zomato,Playstore

In [17]:
from transformers import pipeline

classifier=pipeline("zero-shot-classification",model="MoritzLaurer/deberta-v3-base-zeroshot-v1.1-all-33",device=0,batch_size=4)

In [41]:
themes = [
    "late delivery or delayed order",
    "order not delivered or missing items",
    "wrong order received",
    "food quality issue (cold stale bad taste)",
    "refund delay or refund not received",
    "no response from customer support",
    "delivery partner behavior issue",
    "high pricing or extra charges",
    "payment failure or refund processing issue",
    "app crash or technical problem",
]
review = "Food was great but I've been waiting 12 days for my refund and support never replied"

result = classifier(review, candidate_labels=themes, multi_label=True)
print(result['labels'][:2], result['scores'][:2])

You seem to be using the pipelines sequentially on GPU. In order to maximize efficiency please use a dataset

['no response from customer support', 'refund delay or refund not received'] [0.9997071623802185, 0.9992056488990784]

In [24]:
from tqdm import tqdm

In [40]:
label_map = {
    "late delivery or delayed order": "late_delivery",
    "order not delivered or missing items": "order_missing",
    "wrong order received": "wrong_order",
    "food quality issue (cold stale bad taste)": "food_quality",
    "refund delay or refund not received": "refund_issue",
    "no response from customer support": "no_support",
    "delivery partner behavior issue": "delivery_behavior",
    "high pricing or extra charges": "pricing_issue",
    "payment failure or refund processing issue": "payment_issue",
    "app crash or technical problem": "app_issue"
}

In [57]:
sample_df=reviews_df
sample_df = sample_df[sample_df['score'] <= 3]
sample_df = sample_df[sample_df['content'].str.len() > 15]
sample_df

,content,score,ThumbsUpCount,at,AppVersion,app,platform
3,it cannot deliver in villages like agiaon bazar,2,0,2026-03-26 17:25:20,None,Zomato,Playstore
6,worst application.,1,0,2026-03-26 17:01:16,18.9.5,Zomato,Playstore
9,waste delivery app in the world don't download it,1,0,2026-03-26 16:11:24,19.4.7,Zomato,Playstore
15,Day by Day you guys are going worst. People ma...,1,0,2026-03-26 15:14:47,19.4.7,Zomato,Playstore
18,the service has been degrading for last 2 mont...,1,0,2026-03-26 15:07:07,None,Zomato,Playstore
...,...,...,...,...,...,...,...
29951,I often order from the KFC outlet at Nicco Par...,2,2,2026-02-22 16:59:34,19.3.7,Zomato,Playstore
29963,"""Very disappointing experience with Zomato! I ...",1,0,2026-02-22 16:48:33,19.3.7,Zomato,Playstore
29968,zomato best option 👍,3,0,2026-02-22 16:44:21,19.3.7,Zomato,Playstore
29980,"worst app, can't cancel order, zomato will los...",1,0,2026-02-22 16:30:18,19.1.0,Zomato,Playstore
29985,always shows not delivered,1,0,2026-02-22 16:27:49,19.3.7,Zomato,Playstore

In [65]:
results = []
for out in tqdm(
    classifier(sample_df['content'].tolist(), candidate_labels=themes, multi_label=True, batch_size=8),
    total=len(sample_df),
    desc="Classifying"
):
    pairs = sorted(zip(out['labels'], out['scores']), key=lambda x: x[1], reverse=True)
    tags = {short: 0 for short in label_map.values()}
    count = 0
    for label, score in pairs:
        if score >= 0.70 and count < 2:
            tags[label_map[label]] = 1
            count += 1
    results.append(tags)

tagged = pd.DataFrame(results)
df_final = pd.concat([sample_df.reset_index(drop=True), tagged], axis=1)

Classifying: 100%|██████████| 3462/3462 [00:00<00:00, 234378.42it/s]

In [72]:
df_final

,content,score,ThumbsUpCount,at,AppVersion,app,platform,late_delivery,order_missing,wrong_order,food_quality,refund_issue,no_support,delivery_behavior,pricing_issue,payment_issue,app_issue
0,it cannot deliver in villages like agiaon bazar,2,0,2026-03-26 17:25:20,None,Zomato,Playstore,0,0,0,0,0,0,0,0,0,0
1,worst application.,1,0,2026-03-26 17:01:16,18.9.5,Zomato,Playstore,0,0,0,0,0,0,0,0,0,0
2,waste delivery app in the world don't download it,1,0,2026-03-26 16:11:24,19.4.7,Zomato,Playstore,0,0,0,0,0,0,0,0,0,0
3,Day by Day you guys are going worst. People ma...,1,0,2026-03-26 15:14:47,19.4.7,Zomato,Playstore,0,0,0,0,0,1,1,0,0,0
4,the service has been degrading for last 2 mont...,1,0,2026-03-26 15:07:07,None,Zomato,Playstore,1,1,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3457,I often order from the KFC outlet at Nicco Par...,2,2,2026-02-22 16:59:34,19.3.7,Zomato,Playstore,0,1,0,0,0,0,1,0,0,0
3458,"""Very disappointing experience with Zomato! I ...",1,0,2026-02-22 16:48:33,19.3.7,Zomato,Playstore,0,1,0,0,0,0,1,0,0,0
3459,zomato best option 👍,3,0,2026-02-22 16:44:21,19.3.7,Zomato,Playstore,0,0,0,0,0,0,0,0,0,0
3460,"worst app, can't cancel order, zomato will los...",1,0,2026-02-22 16:30:18,19.1.0,Zomato,Playstore,0,0,0,0,0,0,0,0,0,0
3461,always shows not delivered,1,0,2026-02-22 16:27:49,19.3.7,Zomato,Playstore,1,1,0,0,0,0,0,0,0,0

In [78]:
from sqlalchemy import  create_engine,text
engine=create_engine('mysql+pymysql://root:1234@localhost:3306/Review_analysis',
                     echo=False)

In [79]:
df_final.to_sql('classified_reviews', engine, if_exists='replace', index=False)
reviews_df.to_sql('reviews', engine, if_exists='replace', index=False)

30000